apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "server.fullname" . }}
  labels:
    app: {{ template "server.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "server.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "server.fullname" . }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: server
        image: "{{ .Values.imagePrefix}}{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        tty: true
        stdin: true
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: MAXPLAYERS
          value: {{ .Values.server.maxplayers | quote }}
        - name: SV_HOSTNAME
          value: {{ .Values.server.name | quote }}
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "server.fullname" . }}
              key: rcon_password
        - name: MAP
          value: {{ .Values.server.map | quote }}
        - name: MAPCYCLE
          value: |
{{ join "\n" .Values.server.mapcycle | indent 12 }}
        - name: WINLIMIT
          value: {{ .Values.server.winlimit | quote }}
        {{- if .Values.server.sv_password }}
        - name: SV_PASSWORD
          value: {{.Values.server.sv_password }}
        {{- end }}
        ports:
        - name: server
          containerPort: 27015
          protocol: UDP
        - name: rcon
          containerPort: 27015
          protocol: TCP
      
