apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 10.10.99.0-10.10.99.255
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example-advertisement3
  namespace: metallb-system
spec:
  ipAddressPools:
    - default
  interfaces: # this interfaces block is recommended if you have bonds/bridge interfaces because ... reasons? filtering what responds to arp or something?
    - br0

# note to self: if you are having trouble getting arp to work... the qlcnics I have sometimes need promiscuous mode turned on
# ... seems like same problem I had in VyOS. TODO: test if same problem happens on other NICs

# install MetalLB:
# kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/master/config/manifests/metallb-native.yaml
