image: origin-docker
imageTag: "latest"
sniImage: sniproxy
sniTag: "latest"
imagePrefix: squid:5000/

resources:
  requests:
    memory: 100Mi
    cpu: 1

server:
  storage:
    hostname: kubeworker3
    path: /data/cache-data
