image: origin-docker
imageTag: "20181025-181206"
sniImage: sniproxy
sniTag: "20181023-143613"
imagePrefix: "dockerreg.lanadmins.net/"
imagePullSecret: dockerreglanadminsnet

resources:
  requests:
    memory: 100Mi
    cpu: 1

server:
  storage:
    hostname: cache
    path: /data/cache-data
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "cache"
    effect: "NoSchedule"
  nodeSelector:
    dedicated: "cache"

