apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "server.fullname" . }}
  labels:
    app: {{ template "server.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "server.fullname" . }}
    spec:
      containers:
      - name: server
        image: "{{ .Values.imagePrefix}}{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        tty: true
        stdin: true
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: LAN
          value: {{ .Values.server.lan | quote }}
        - name: SV_HOSTNAME
          value: {{ .Values.server.name | quote }}
        - name: MAP
          value: {{ .Values.server.default_map | quote }}
        - name: MAPCYCLEFILE
          value: map_cycle_file
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "server.fullname" . }}
              key: rcon_password
        - name: GAME_TYPE
          value: {{ .Values.server.game_type | quote }}
        - name: GAME_MODE
          value: {{ .Values.server.game_mode | quote }}
          
        ports:
        - name: server
          containerPort: 27015
          protocol: UDP
        - name: rcon
          containerPort: 27015
          protocol: TCP
      