name: tf2-prophunt
version: 0.0.1
appVersion: 0.0.1
description: Team Fortress 2 Prop Hunt
keywords:
- game
- server
- team fortress 2
- prop hunt
home: https://www.opensourcelan.com
sources:
- https://github.com/OpenSourceLAN/gameservers-docker/tree/master/tf2-prophunt
maintainers:
- name: Chris Holman
  email: chris@opensourcelan.com
