image: hl2dm
imageTag: 20221003-065414
imagePrefix: docker.pax.lan/

resources:
  requests:
    memory: 500Mi
    cpu: 500m

server:
  name: HL2DM Server
  description: HL2DM Server
  maxplayers: 16
  mapcycle:
  - dm_lockdown
  - dm_overwatch
  - dm_powerhouse
  - dm_resistance
  - dm_runoff
  - dm_steamlab
  - dm_underpass
  winlimit: 100
  map: dm_resistance
  # If left blank, no password is set
  sv_password:
  # If left blank a password will be generated for you
  rcon_password:

