apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite stop {
          name regex (.*)\.server\.lan {1}.default.svc.cluster.local
          answer name (.*)\.default\.svc\.cluster\.local {1}.server.lan
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        reload
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system

