apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-server-redirector
  namespace: kube-system
  labels:
    app: dns-server-redirector
spec:
  selector:
    matchLabels:
      app: dns-server-redirector
  template:
    metadata:
      labels:
        app: dns-server-redirector
    spec:
      containers:
      - name: dns-server-director
        image: andyshinn/dnsmasq
        args:
        # effectively disables forwarding of queries
        - -R
        # Except forward this specific domain to this server
        - -S
        - /server.lan/10.96.0.10
        resources:
          requests:
            cpu: "10m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
---
# This service uses metallb
# install: https://metallb.universe.tf/installation/
# and then configure a `default` address pool https://metallb.universe.tf/configuration/
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  name: test
  namespace: kube-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: dns-server-redirector
  sessionAffinity: None
  type: LoadBalancer
