apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ut2004.fullname" . }}
  labels:
    app: {{ template "ut2004.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "ut2004.fullname" . }}
    spec:
      containers:
      - name: ut2004
        image: "{{ .Values.imagePrefix}}{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: SV_HOSTNAME
          value: {{ .Values.server.name | quote }}
        {{- if .Values.server.rcon_password }}
        - name: RCON_PASSWORD
          value: {{ .Values.server.rcon_password | quote }}
        {{- end }}
        {{- if .Values.server.game_password }}
        - name: SV_PASSWORD
          value: {{ .Values.server.game_password | quote }}
        {{- end }}
        {{- if .Values.server.instagib }}
        - name: INSTAGIB
          value: {{ .Values.server.instagib | quote }}
        {{- end }}
        {{- if .Values.server.mutators }}
        - name: MUTATORS
          value: {{ .Values.server.mutators | quote }}
        {{- end }}
        - name: MAP
          value: {{ .Values.server.map | quote }}
        - name: MAXPLAYERS
          value: {{ .Values.server.maxplayers | quote }}
        {{- if .Values.server.lan }}
        - name: LAN
          value: "1"
        {{- end }}
        {{- if .Values.server.other_opts }}
        - name: OTHER_OPTS
          value: {{ .Values.server.other_opts | quote }}
        {{- end }}
        ports:
        - name: ut2004
          containerPort: 7779
          protocol: UDP
      