apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "unreal4.fullname" . }}
  labels:
    app: {{ template "unreal4.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "unreal4.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "unreal4.fullname" . }}
    spec:
      imagePullSecrets:
      - name: dockerreglanadminsnet
      containers:
      - name: unreal4
        image: "{{ .Values.imagePrefix}}{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: SV_HOSTNAME
          value: {{ .Values.server.name | quote }}
        {{- if .Values.server.rcon_password }}
        - name: RCON_PASSWORD
          value: {{ .Values.server.rcon_password | quote }}
        {{- end }}
        {{- if .Values.server.game_password }}
        - name: SV_PASSWORD
          value: {{ .Values.server.game_password | quote }}
        {{- end }}
        - name: MAP
          value: {{ .Values.server.map | quote }}
        - name: MAXPLAYERS
          value: {{ .Values.server.maxplayers | quote }}
        {{- if .Values.server.timelimit }}
        - name: TIMELIMIT
          value: {{ .Values.server.timelimit | quote }}
        {{- end }}
        {{- if .Values.server.goalscore }}
        - name: GOALSCORE
          value: {{ .Values.server.goalscore | quote }}
        {{- end }}
        {{- if .Values.server.timelimit }}
        - name: TIMELIMIT
          value: {{ .Values.server.timelimit | quote }}
        {{- end }}
        {{- if .Values.server.goalscore }}
        - name: GOALSCORE
          value: {{ .Values.server.goalscore | quote }}
        {{- end }}
        ports:
        - name: unreal4
          containerPort: 7779
          protocol: UDP
      
---

apiVersion: v1
kind: Service
metadata:
  name: unreal1
spec:
  selector:
    app: {{ template "unreal4.fullname" . }}
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 123
